name: iOS Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build iOS App
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Resolve Swift Packages
      #   run: xcodebuild -resolvePackageDependencies

      - name: Build
        run: |
          xcodebuild \
            -scheme MBatmaN\
            -destination 'platform=iOS Simulator,name=iPhone 17 Pro Max' \
            CODE_SIGNING_ALLOWED=NO \
            build
